### ISSUE TITLE
Add feed

### ISSUE THREAD

**Issue by rgaiacs** [dpshelio/dpshelio.github.io#3]
I want to add your blog to my RSS/Atom feed list. Could you add

~~~
plugins:
- jekyll-feed
~~~

into `_config.yml` and

~~~
{% feed_meta %}
~~~

after https://github.com/dpshelio/dpshelio.github.io/blob/master/_layouts/default.html#L3.

Thanks in advance.

**Comment by dpshelio** [comment]
:) Thank you!!! I'll do!! I know I've got to fix that since a while!! now I've got a reason!! people is following me!! 🎉
